### ISSUE TITLE
fix build with clang/FreeBSD

### ISSUE THREAD

**Issue by phfaist** [klatexformula/klatexformula#14]
[auto-migrated] Reported by **isly** on sf.net [klatexformula/bugs/14](https://sourceforge.net/p/klatexformula/bugs/14)

klatexformula fails to build on recent FreeBSD with clang-3.4 (build log for 3.2.7, but 3.2.8 has the same problem):

[ 86%] Building CXX object src/CMakeFiles/klatexformula.dir/main.cpp.o
cd /wrkdirs/usr/ports/graphics/klatexformula/work/.build/src && /usr/bin/c++   -DKLFBACKEND_QT4 -DKLF_CMAKE_ARCH=\"amd64\" -DKLF_LIBKLFTOOLS_STATIC -DKLF_SHARE_DIR=\"../share/klatexformula\" -DKLF_SHARE_RCCRESOURCES_DIR=\"../share/klatexformula/rccresources\" -DKLF_SRC_BUILD -DKLF_USE_DBUS -DKLF_VERSION_MAJ=3 -DKLF_VERSION_MIN=2 -DKLF_VERSION_REL=7 -DKLF_VERSION_STRING=\"3.2.7\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -I/usr/local/include  -I/usr/local/include -DQT_NO_DEBUG_OUTPUT -I/wrkdirs/usr/ports/graphics/klatexformula/work/.build/src -I/wrkdirs/usr/ports/graphics/klatexformula/work/klatexformula-3.2.7/src -isystem /usr/local/include/qt4 -isystem /usr/local/include/qt4/QtGui -isystem /usr/local/include/qt4/QtDBus -isystem /usr/local/include/qt4/QtXml -isystem /usr/local/include/qt4/QtSql -isystem /usr/local/include/qt4/QtCore -I/wrkdirs/usr/ports/graphics/klatexformula/work/klatexformula-3.2.7/src/klftools -I/wrkdirs/usr/ports/graphics/kl
 atexformula/work/klatexformula-3.2.7/src/klfbackend -o CMakeFiles/klatexformula.dir/main.cpp.o -c /wrkdirs/usr/ports/graphics/klatexformula/work/klatexformula-3.2.7/src/main.cpp
/wrkdirs/usr/ports/graphics/klatexformula/work/klatexformula-3.2.7/src/main.cpp:527:33: error: redefinition of default argument
void dumpDir(const QDir& d, int indent = 0)
                                ^        ~
/wrkdirs/usr/ports/graphics/klatexformula/work/klatexformula-3.2.7/src/main.cpp:521:33: note: previous definition is here
  void dumpDir(const QDir&, int = 0);
                                ^ ~
/wrkdirs/usr/ports/graphics/klatexformula/work/klatexformula-3.2.7/src/main.cpp:542:5: error: use of undeclared identifier 'dumpDir'
    dumpDir(QDir(d.absoluteFilePath(dchildren[k])), indent+1);
    ^
2 errors generated.
*** Error code 1

[attachments not auto-migrated -> [klatexformula/bugs/14](https://sourceforge.net/p/klatexformula/bugs/14)]
